version: "3.7"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: asstec192/samu-dashboard:0.5.01
    environment:
      - DATABASE_URL=sqlserver://172.21.13.177;database=ESUSSAMU5;user=sa;password=MedboX2008;encrypt=true;TrustServerCertificate=true
      - NEXTAUTH_SECRET=vZpSTe7hjWsKNlLhyD+PQ74bJFgtMeF34tVOe8T9obM=
      - NEXTAUTH_URL=http://172.21.13.171:3000
