import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";
import { ModalOcorrencia } from "@/components/dialogs/ModalOcorrencia";
import { NextAuthProvider } from "@/providers/NextAuthProvider";
import { NextQueryParamProvider } from "@/providers/NextQueryParamProvider";
import { Toaster } from "@/components/ui/toaster";
import { Navbar } from "@/components/navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} flex flex-col overflow-auto`}
      >
        <TRPCReactProvider cookies={cookies().toString()}>
          <NextAuthProvider>
            <Navbar />
            <Toaster />
            <NextQueryParamProvider>{children}</NextQueryParamProvider>
            <ModalOcorrencia />
          </NextAuthProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
